#!/usr/bin/env bash
#Topology CSV to be in format NAME,Console,MGMT IP

if [ $# -lt 2 ]; then
	echo "Usage: cyg_topo_all <topology> <console/mgmt> [log]"
	echo "		 topology is csv file location"
	echo "NOTE: This currently works only for 6 windows, since window size is fixed"
	echo "		For more number of nodes, use cyg_topo instead"
	exit
fi

CSVFILE=$1

if [ -f $CSVFILE ]; then
	echo "Topology file $CSVFILE found"
else
	echo "FILE $CSVFILE not found"
	exit
fi

if [[ "${2,,}" == c* ]]; then
	echo "Console Connection"
	column=2;
elif [[ "${2,,}" == m* ]]; then
	echo "MGMT connection"
	column=3;
else
	echo "%Error: Invalid connection type mentioned. Select console/mgmt"
	exit
fi

#Works only for 6 nodes currently.
lineCount=`grep -v "^#" $CSVFILE | wc -l`
echo "Line Count: $lineCount"
if [ $lineCount -gt 6 ] ; then
	echo "%Error: Script works currently only for 6 nodes in topology"
	exit
fi

log=0
if [[ "${3,,}" == l* ]]; then
	log=1
	ts=`date +"%d-%b-%Y_%H_%M%S"`
	logDir=$HOME/logs/ctopo_all_${CSVFILE##*/}_$2_$ts
	echo "Log path: $logDir"
	mkdir -p $logDir
fi

index=1
x=0
y=0
orientation=0 #right=1 or down=0
for i in `cut -d',' -f1 $CSVFILE`
do
	if [[ $i == \#* ]] ;
	then
		echo "Skipping $i"
		index=$(expr $index + 1);
		continue;
	fi
	echo "Telnet to $i $x X $y ..."
	IP=`sed -n "$index"p $CSVFILE | cut -d',' -f$column -`;
	NODE=`sed -n "$index"p $CSVFILE | cut -d',' -f1 -`;
	opt="-p $x,$y -s 105,17 --Title "$2_$NODE""
	if [ "$log" = "1" ] ; then
		ts=`date +"%d-%b-%Y_%H_%M%S"`
		logFile=$logDir/$NODE\_$ts.log
		echo "logging to $logFile"
		opt="$opt -l $logFile"
	fi
	echo "NODE: $NODE : IP $IP"
	$MYTTY $opt --exec telnet $IP &
	index=$(expr $index + 1);
	if [ $orientation -eq 1 ] ; then
		y=$(expr $y + 270);
		x=0;
		orientation=0;
	else
		x=$(expr $x + 770);
		orientation=1;
	fi
done
