#!/bin/bash
#Topology CSV to be in format NAME,Console,MGMT IP

if [ $# -lt 2 ]; then
	echo "Usage: cyg_topo <topology> <console/mgmt>"
	echo "		 topology is csv file location"
	exit
fi

CSVFILE=$1

if [ -f $CSVFILE ]; then
	echo "Topology file $CSVFILE found"
else
	echo "FILE $CSVFILE not found"
	exit
fi

if [[ "${2,,}" == c* ]]; then
	echo "Console Connection"
	column=2;
elif [[ "${2,,}" == m* ]]; then
	echo "MGMT connection"
	column=3;
else
	echo "%Error: Invalid connection type mentioned. Select console/mgmt"
	exit
fi

#Works only for 6 nodes currently.
lineCount=`grep -v "^#" $CSVFILE | wc -l`
echo "Line Count: $lineCount"
if [ $lineCount -gt 6 ] ; then
	echo "%Error: Script works currently only for 6 nodes in topology"
	exit
fi

index=1
x=0
y=0
orientation=0 #right=1 or down=0
for i in `cut -d',' -f1 $CSVFILE`
do
	if [[ $i == \#* ]] ;
	then
		echo "Skipping $i"
		index=$(expr $index + 1);
		continue;
	fi
	echo "Telnet to $i $x X $y ..."
	IP=`sed -n "$index"p $CSVFILE | cut -d',' -f$column -`;
	NODE=`sed -n "$index"p $CSVFILE | cut -d',' -f1 -`;
	echo "NODE: $NODE : IP $IP"
	$MYTTY -p $x,$y -s 114,18 --Title "$2_$NODE" --exec telnet $IP &
	index=$(expr $index + 1);
	if [ $orientation -eq 1 ] ; then
		y=$(expr $y + 350);
		x=0;
		orientation=0;
	else
		x=$(expr $x + 952);
		orientation=1;
	fi
done
