#!/bin/bash

if [ $# -lt 2 ]; then
	echo "Usage: cyg_topo <topology> <console/mgmt>"
	echo "		 topology is csv file location"
	exit
fi

CSVFILE=$1

if [ -f $CSVFILE ]; then
	echo "Topology file $CSVFILE found"
else
	echo "FILE $CSVFILE not found"
	exit
fi

if [[ "${2,,}" == c* ]]; then
	echo "Console Connection"
	column=2;
fi

if [[ "${2,,}" == m* ]]; then
	echo "MGMT connection"
	column=3;
fi

echo "0) ALL"
select NODE in `cut -d',' -f1 $CSVFILE`;
do
	echo "you selected $NODE";
	if [ "$REPLY" = "0" ] ; then 
		index=1
		for i in `cut -d',' -f1 $CSVFILE`
		do
			echo "Telnet to $i..."
			IP=`sed -n "$index"p $CSVFILE | cut -d',' -f$column -`;
			NODE=`sed -n "$index"p $CSVFILE | cut -d',' -f1 -`;
			echo "NODE: $NODE : IP $IP"
			mintty --title "$2_$NODE" --exec telnet $IP &
			index=$(expr $index + 1);
		done
		break; 
	fi
	if [ -n $NODE ] ; then
		IP=`sed -n "$REPLY"p $CSVFILE | cut -d',' -f$column -`;
		echo "console $IP"
		mintty --title "$2_$NODE" --exec telnet $IP &
	fi
done
