#!/usr/bin/env bash
#Topology CSV to be in format NAME,Console,MGMT IP

if [ $# -lt 2 ]; then
	echo "Usage: cyg_topo <topology> <console/mgmt> [log]"
	echo "		 topology is csv file location"
	exit
fi

CSVFILE=$1

if [ -f $CSVFILE ]; then
	echo "Topology file $CSVFILE found"
else
	echo "FILE $CSVFILE not found"
	exit
fi

if [[ "${2,,}" == c* ]]; then
	echo "Console Connection"
	column=2;
elif [[ "${2,,}" == m* ]]; then
	echo "MGMT connection"
	column=3;
else
	echo "%Error: Invalid connection type mentioned. Select console/mgmt"
	exit
fi

log=0
if [[ "${3,,}" == l* ]]; then
	log=1
	ts=`date +"%d-%b-%Y_%H_%M%S"`
	logDir=$HOME/logs/ctopo_${CSVFILE##*/}_$2_$ts
	echo "Log path: $logDir"
	mkdir -p $logDir
fi

echo "Will spawn $MYTTY terminal depending on below selection"

CSVDATA=$(grep -v '^#' $CSVFILE)
echo "0) ALL"
select NODE in `echo "$CSVDATA" | cut -d',' -f1`;
do
	echo "you selected $NODE";
	if [ "$REPLY" = "0" ] ; then 
		index=1
		index=1
		x=0
		y=0
		orientation=0 #right=1 or down=0
		for i in `echo "$CSVDATA" | cut -d',' -f1`
		do
			if [[ $i == \#* ]] ;
			then
				echo "Skipping $i"
				index=$(expr $index + 1);
				continue;
			fi
			echo "Telnet to $i..."
			IP=`echo "$CSVDATA" | sed -n "$index"p | cut -d',' -f$column -`;
			NODE=`echo "$CSVDATA" | sed -n "$index"p | cut -d',' -f1 -`;
			echo "NODE: $NODE : IP $IP"
			#opt="-p $x,$y -s 105,17 --Title "$2_$NODE""
			opt="-p $x,$y -s 92,15 --fs 9 --Title "$2_$NODE""
			if [ "$log" = "1" ] ; then
				ts=`date +"%d-%b-%Y_%H_%M%S"`
				logFile=$logDir/$NODE\_$ts.log
				echo "logging to $logFile"
				opt="$opt -l $logFile"
			fi
			$MYTTY $opt --exec telnet $IP &
			index=$(expr $index + 1);
			if [ $orientation -eq 1 ] ; then
				y=$(expr $y + 270);
				x=0;
				orientation=0;
			else
				x=$(expr $x + 770);
				orientation=1;
			fi
		done
		#break; 
	fi
	if [ -n $NODE ] ; then
		IP=`echo "$CSVDATA" | sed -n "$REPLY"p | cut -d',' -f$column -`;
		echo "Console $IP"
		#opt="-s 105,17 --Title "$2_$NODE""
		opt="-s 92,15 --fs 9 --Title "$2_$NODE""
		if [ "$log" = "1" ] ; then
			ts=`date +"%d-%b-%Y_%H_%M%S"`
			logFile=$logDir/$NODE\_$ts.log
			echo "logging to $logFile"
			opt="$opt -l $logFile"
			opt="$opt -l $logFile"
		fi
		$MYTTY $opt --exec telnet $IP &
	fi
done
