#!/bin/bash

echo "Install necessary packages"
sudo apt-get install git gcc bison flex screen cscope vim build-essential module-assistant iperf libncurses5-dev make exuberant-ctags bc libssl-dev curl svn
sudo m-a prepare

unlink $HOME/.vimrc
unlink $HOME/.bashrc
unlink $HOME/.sccreenrc
ln -s $HOME/git/Linux/vim/.vimrc $HOME/.vimrc
ln -s $HOME/git/Linux/bash_aliases/.bashrc $HOME/.bashrc 
ln -s $HOME/git/Linux/screen/.screenrc $HOME/.screenrc

mkdir -p ~/.vim/bundle
mkdir -p ~/.vim/autoload
cd ~/.vim/autoload
wget https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim 

cd ~/.vim/bundle
mkdir -p ~/.vim/bundle/vim-gitgutter/autoload
mkdir -p ~/.vim/bundle/vim-gitgutter/plugin
cd ~/.vim/bundle/vim-gitgutter/plugin
wget  wget https://raw.githubusercontent.com/airblade/vim-gitgutter/master/plugin/gitgutter.vim
cd ~/.vim/bundle/vim-gitgutter/autoload
svn export https://github.com/airblade/vim-gitgutter/trunk/autoload/gitgutter
wget https://raw.githubusercontent.com/airblade/vim-gitgutter/master/autoload/gitgutter.vim
