#!/bin/bash

echo "Install necessary packages"
sudo apt-get install git gcc bison flex screen cscope vim build-essential module-assistant iperf libncurses5-dev make exuberant-ctags bc libssl-dev curl svn
#sudo apt-get install lttng-tools
sudo m-a prepare

unlink $HOME/.vimrc
unlink $HOME/.bashrc
unlink $HOME/.screenrc
ln -s $HOME/git/Linux/vim/.vimrc $HOME/.vimrc
ln -s $HOME/git/Linux/bash_aliases/.bashrc $HOME/.bashrc 
ln -s $HOME/git/Linux/bash_aliases/.bash_profile $HOME/.bash_profile
ln -s $HOME/git/Linux/screen/.screenrc $HOME/.screenrc

mkdir -p ~/.vim/bundle
mkdir -p ~/.vim/autoload
cd ~/.vim/autoload
wget --no-check-certificate https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim 

cd ~/.vim/bundle
mkdir -p ~/.vim/bundle/vim-gitgutter/autoload
mkdir -p ~/.vim/bundle/vim-gitgutter/plugin
cd ~/.vim/bundle/vim-gitgutter/plugin
wget --no-check-certificate https://raw.githubusercontent.com/airblade/vim-gitgutter/master/plugin/gitgutter.vim
wget --no-check-certificate https://raw.githubusercontent.com/tpope/vim-fugitive/master/plugin/fugitive.vim
cd ~/.vim/bundle/vim-gitgutter/autoload
svn export https://github.com/airblade/vim-gitgutter/trunk/autoload/gitgutter
wget --no-check-certificate https://raw.githubusercontent.com/airblade/vim-gitgutter/master/autoload/gitgutter.vim

cd $HOME/.vim/bundle
git clone https://github.com/tpope/vim-fugitive.git

if [ -f $HOME/.gitconfig ]; then
	echo "[diff]" >> $HOME/.gitconfig
	echo "	tool = vimdiff" >> $HOME/.gitconfig
	echo "[difftool]" >> $HOME/.gitconfig
	echo "	prompt = false" >> $HOME/.gitconfig
fi
